In [1]:
# Question 1: Check if a number is even
def is_even(x):
    return x % 2 == 0

# Question 2: Reverse a string
def reverse_string(x):
    return x[::-1]

# Question 3: Find the maximum number in a list
def find_max(x):
    a = float('-inf')
    for n in x:
        if a < n:
            a = n
    return a

# Question 4: Calculate the factorial of a number
def factorial(x):
    fact = 1
    if x == 0:
        return 1
    for n in range(1, x + 1):
        fact *= n
    return fact

# Question 5: Generate the nth Fibonacci number
def fibonacci(x):
    if x == 1:
        return 1
    if x == 0:
        return 0
    return fibonacci(x - 1) + fibonacci(x - 2)

# Question 6: Check if a string is a palindrome
import re

def is_palindrome(x):
    x = re.sub(r'[^A-Za-z0-9]', '', x)
    return x.lower() == x[::-1].lower()

# Question 7: Check if two strings are anagrams
import re

def is_anagram(x, y):
    x = re.sub(r'[^A-Za-z0-9]', '', x)
    y = re.sub(r'[^A-Za-z0-9]', '', y)
    return sorted(x.lower()) == sorted(y.lower())

# Question 8: Check if a number is prime
import math

def is_prime(x):
    if x <= 1:
        return False
    for n in range(2, int(math.sqrt(x)) + 1):
        if x % n == 0:
            return False
    return True

# Question 9: Check if a number is an Armstrong number
def is_armstrong(x):
    if x < 0:
        return False
    num = str(x)
    total = sum(int(digit) ** len(num) for digit in num)
    return total == x

# Question 10: Count the number of vowels in a string
def count_vowels(x):
    vowels = {'a', 'e', 'i', 'o', 'u'}
    return sum(1 for char in x if char.lower() in vowels)

def second_largest(x):
    unique = list(set(x))
    if len(unique)<=2:
        return None
    unique.sort()
    return unique[-2]
print(second_largest([10, 20, 4, 45, 99]))  # Output: 45
print(second_largest([1, 1, 1, 1]))         # Output: None
print(second_largest([2]))                 # Output: None

import re
def count_unique_words(x):
    x=re.sub(r'[^A-Za-z]'," ",x)
    x = x.lower().split()
    x = list(set(x))
    return len(x)
print(count_unique_words("Hello world! Hello again."))  # Output: 3
print(count_unique_words("Python is fun. Python is awesome."))  # Output: 4
print(count_unique_words(""))  # Output: 0

print('====================================')
def longest_word(x):
    x = re.sub(r'[^A-Za-z\s]', '', x) 
    words = x.split()
    if not words:  
        return ""
    return max(words, key=len) 

print(longest_word("The quick brown fox jumped over the lazy dog."))  # Output: "jumped"
print(longest_word("Python programming is fun!"))                    # Output: "programming"
print(longest_word(""))  # Output: ""

45
None
None
3
4
0
jumped
programming



In [2]:
# Test for Question 1: Check if a number is even
print(is_even(4))  # Output: True
print(is_even(7))  # Output: False

# Test for Question 2: Reverse a string
print(reverse_string("hello"))  # Output: "olleh"
print(reverse_string("world"))  # Output: "dlrow"

# Test for Question 3: Find the maximum number in a list
print(find_max([1, 2, 3, 4, 5]))  # Output: 5
print(find_max([-10, -20, -5, -1]))  # Output: -1

# Test for Question 4: Calculate the factorial of a number
print(factorial(5))  # Output: 120
print(factorial(0))  # Output: 1

# Test for Question 5: Generate the nth Fibonacci number
print(fibonacci(5))  # Output: 5
print(fibonacci(10))  # Output: 55

# Test for Question 6: Check if a string is a palindrome
print(is_palindrome("madam"))  # Output: True
print(is_palindrome("hello"))  # Output: False
print(is_palindrome("A man, a plan, a canal, Panama"))  # Output: True

# Test for Question 7: Check if two strings are anagrams
print(is_anagram("listen", "silent"))  # Output: True
print(is_anagram("hello", "world"))  # Output: False

# Test for Question 8: Check if a number is prime
print(is_prime(7))  # Output: True
print(is_prime(10))  # Output: False

# Test for Question 9: Check if a number is an Armstrong number
print(is_armstrong(153))  # Output: True
print(is_armstrong(123))  # Output: False

# Test for Question 10: Count the number of vowels in a string
print(count_vowels("hello world"))  # Output: 3
print(count_vowels("python"))  # Output: 1

# Test for second largest
print(second_largest([10, 20, 4, 45, 99]))  # Output: 45
print(second_largest([1, 1, 1, 1]))         # Output: None
print(second_largest([2]))                 # Output: None

# Test for count unique words
print(count_unique_words("Hello world! Hello again."))  # Output: 3
print(count_unique_words("Python is fun. Python is awesome."))  # Output: 4
print(count_unique_words(""))  # Output: 0

# Test for longest word
print(longest_word("The quick brown fox jumped over the lazy dog."))  # Output: "jumped"
print(longest_word("Python programming is fun!"))                    # Output: "programming"
print(longest_word(""))  # Output: ""


True
False
olleh
dlrow
5
-1
120
1
5
55
True
False
True
True
False
True
False
True
False
3
1
45
None
None
3
4
0
jumped
programming



In [4]:
import numpy as np

a = np.diag([1,1,1,1,1])
print(a)

print("===============================================")
b = np.linspace(0,1,20)
print(b)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [13]:
from numpy import random
a = np.random.randint(1, 11, (3, 3))  # Random integers between 1 and 10
b = np.random.randint(1, 11, (3, 3))  # Random integers between 1 and 10

# Element-wise operations
print("Element-wise Addition:\n", a + b)
print("\nElement-wise Subtraction:\n", a - b)
print("\nElement-wise Multiplication:\n", a * b)


Element-wise Addition:
 [[18 10 14]
 [ 8 14  5]
 [14 14 13]]

Element-wise Subtraction:
 [[ 0 -4 -2]
 [ 2  6  3]
 [-2  6  5]]

Element-wise Multiplication:
 [[81 21 48]
 [15 40  4]
 [48 40 36]]
